application: nc-jb-map
version: 9
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /tiles
  static_dir: tiles
  expiration: "1d"

- url: /images
  static_dir: images

- url: /.*
  script: map.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.tmp$
- ^(.*/)?.*\.sh$
- ^(.*/)?.*/.svn/.*
- ^(.*/)?.*bulkloader.*

builtins:
- datastore_admin: on
- remote_api: on

derived_file_type:
- python_precompiled
