application: nc-jb-map
version: 3
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /tiles
  static_dir: tiles

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  script: map.py

derived_file_type:
- python_precompiled
