application: nc-jb-map
version: 12
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /feeds/.*
  script: feeds.py

- url: /editor.*
  script: editor.py
  login: required

- url: /admin.*
  script: admin.py
  login: admin

- url: /worker
  script: worker.py

- url: /.*
  script: map.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.tmp$
- ^(.*/)?.*\.sh$
- ^(.*/)?.*/.svn/.*
- ^(.*/)?.*bulkloader.*
- ^(.*/)?.*tiles.*
- ^(.*/)?.*\.jpg
- ^(.*/)?.*\.csv
- ^(.*/)?.*\.php

builtins:
- datastore_admin: on
- remote_api: on

derived_file_type:
- python_precompiled
